---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: etcd-01
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - etcd
  - name: etcd-02
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - etcd
  - name: etcd-03
    image: solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - etcd
provisioner:
  name: ansible
  playbooks:
    setup: ../resources/playbooks/create.yml
    teardown: ../resources/playbooks/destroy.yml
    converge: ../resources/playbooks/playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: ubuntu
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
