---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: etcd-01
    image: molecule_local/solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - etcd
    dockerfile: Dockerfile.ubuntu
  - name: etcd-02
    image: molecule_local/solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - etcd
    dockerfile: Dockerfile.ubuntu
  - name: etcd-03
    image: molecule_local/solita/ubuntu-systemd:latest
    privileged: True
    command: /sbin/init
    groups:
      - etcd
    dockerfile: Dockerfile.ubuntu
    lint:
      name: ansible-lint
provisioner:
  name: ansible
  playbooks:
    setup: ../resources/playbooks/create.yml
    teardown: ../resources/playbooks/destroy.yml
    converge: ../resources/playbooks/playbook.yml
scenario:
  name: ubuntu
verifier:
  name: testinfra
  directory: ../resources/tests/
  lint:
    name: flake8
